version: 2
jobs:
  build:
    docker:

      - image: circleci/node:6

    working_directory: ~/flights_cache_admin

    dependencies:
      override:
        - yarn
      cache_directories:
        - ~/.cache/yarn

    steps:

      - checkout

      - setup_remote_docker


      - run:
          name: Running Unit Tests
          command: npm test

      - run:
          name: Creating a Build
          command: npm run build

      - run:
          name: Building Docker Image
          command: docker build --tag flights-cache-admin:1 .

      - run:
          name: Run Docker Image
          command: docker run -p 3000:3000 -e FLIGHTS_CACHE_ADMIN_PROFILE=production flights-cache-admin:1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
